---
- name: "Install virtualization Host"
  hosts: all
  gather_facts: False
  tasks:
    - name: 'Wait 900 seconds for port 22 to become open and contain "OpenSSH"'
      wait_for:
        port: 22
        host: '{{ inventory_hostname }}'
        search_regex: OpenSSH
        delay: 10
        timeout: 900
      vars:
        ansible_connection: local
    - name: install python if missing
      raw: test -e /usr/bin/python3 || apt-get -y install python3
      register: output
      changed_when: output.stdout != ""
    - name: "install git"
      apt:
        name:
          - git
    - name: "Get the scripts"
      git:
        repo: 'https://github.com/goffinet/windows-poc.git'
        dest: /data/windowspoc
        update: yes
    - name: "Install the solution"
      command: 'bash -x /data/windowspoc/setup-hashicorp-host.sh'
    - name: Reboot the Debian or Ubuntu server
      reboot:
        msg: "Reboot initiated by Ansible"
        connect_timeout: 5
        reboot_timeout: 180
        pre_reboot_delay: 0
        post_reboot_delay: 180
        test_command: uptime
    - name: 'Wait 900 seconds for port 22 to become open and contain "OpenSSH"'
      wait_for:
        port: 22
        host: '{{ inventory_hostname }}'
        search_regex: OpenSSH
        delay: 10
        timeout: 900
      vars:
        ansible_connection: local
